version: '3.3'
services:
  db:
    image: "mongo"
    volumes:
      - correctordb:/data/db
      - correctorconfig:/data/configdb
  www:
    ports:
      - "80:80"
    volumes:
      - ./import:/app/import
      - ./export:/app/export
    environment:
      - DB_HOST=db
      - DB_PORT=27017
    depends_on:
      - "db"
    image: "corrector"
volumes:
  correctordb:
    external: true
  correctorconfig: